name: Print the current date from different environments

on: push

jobs:
  ubuntu_date:
    name: Current date from ubuntu runner
    runs-on: ubuntu-latest
    steps:
      - name: Ubuntu date
        run: |
          now=$(date)
          echo "Current date: $now"
  macos_date:
    name: Current date from macos runner
    runs-on: macos-latest
    steps:
      - name: MacOs date
        run: |
          now=$(date)
          echo "Current date: $now"
  window_date:
    name: Current date from windows runner
    runs-on: windows-latest
    steps:
      - name: Windows date
        run: Get-Date
  ubuntu_depends_date:
    name: Get date after runs from other jobs
    runs-on: ubuntu-18.04
    steps:
      - name: Ubuntu date depends on other runs
        run: |
          now=$(date)
          echo "Current date: $now"
    needs:
      - ubuntu_date
      - macos_date
      - windows_date