name: Use custom action from another repo

on: [ push ]

jobs:
  say_hi:
    name: Gretings from the internet
    runs-on: ubuntu-latest
    steps:
      - name: Use custom action
        id: hello
        uses: vsmind/learning-github-custom-action@master
      - name: Greeting time
        run: echo "The time was ${{ steps.hello.outputs.time }}"